### ISSUE TITLE
Questions: parent scope and object keys

### ISSUE THREAD

**Issue by Pimentero** [webdevelopers-eu/jquery-lazy-template#5]
Hi!

Thank you for great lib!

I have some questions regarding templating:

1. Can I somehow get variable from parent scope inside a template? 
2. Can I iterate through object and get key/value pair via template?

**Comment by webdevelopers-eu** [comment]
Hey there! Sounds like you have a good idea in mind! Are you referring to something like this codepen: https://codepen.io/webdevelopers/pen/XWPvoVJ?editors=1011?

If that's the case, go ahead and pull the latest version! I've just added it. Let me know what you think.

**Comment by Pimentero** [comment]
This is exactly what I was looking for! Thank you very much)
